import '../globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import { Header2 } from '../components/header/header2'
import { Footer } from '../components/footer/footer'
import { GoogleAnalytics } from '../components/google-analytics';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%">
          <Header2 />
          {children}
          <Footer />
        </Theme>
      </body>
      <GoogleAnalytics id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ?? ''} />
    </html>
  )
}
