import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AsideFilter } from "./components/asideFilter";
import { Footer } from "../components/footer/footer";
import { Header2 } from "../components/header/header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Trainerayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          accentColor="crimson"
          grayColor="sand"
          radius="large"
          scaling="95%"
        >
          <Header2 />
          <div className="bg-gray-100">
            <div className="container flex flex-row mx-auto pt-8 max-w-[1150px] min-h-full relative">
              <main className="flex flex-col flex-1 relative">{children}</main>
              <aside className="flex flex-col w-1/4">
                <div className="sticky top-[90px]">
                  <AsideFilter />
                </div>
              </aside>
            </div>
          </div>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
